vim.keymap.set('n', '-', ':NvimTreeToggle<CR>')
vim.keymap.set('n','ZZ', '<Nop>')
vim.keymap.set('n','<Down>', 'gj')
vim.keymap.set('n','<Up>', '  gk')
vim.keymap.set('n','j', 'gj')
vim.keymap.set('n','k', 'gk')
vim.keymap.set('n','h', '<Left>zv')
vim.keymap.set('n','l', '<Right>zv')
vim.keymap.set('n','Y', 'y$')
vim.keymap.set('n','<Leader><S-\\>', ':vertical<CR>')
vim.keymap.set('n','<Leader>-', ':split<CR>')
vim.keymap.set('n','<Leader><C-B>', ':Rooter<CR>:Telescope buffers<CR>')
vim.keymap.set('n','<Leader><C-R>', ':Telescope live_grep<CR>')
vim.keymap.set('n','<Leader><C-L>', ':Telescope grep_string<CR>')
vim.keymap.set('n','<Leader><C-G>', ':Telescope git_files<CR>')
vim.keymap.set('n','<Leader><C-Q>', ':Telescope quickfix<CR>')
vim.keymap.set('n','<Leader><C-Y>', ':Telescope neoclip<CR>')
vim.keymap.set('n','<Leader>w', ':w!<CR>')
vim.keymap.set('n','-', ':NvimTreeToggle<CR>')
vim.keymap.set('n','<Leader>y', ':NvimTreeFindFile<CR>')
vim.keymap.set('n','<silent>', '<Leader>sj :SplitjoinJoin<CR>')
vim.keymap.set('n','<silent>', '<Leader>ss :SplitjoinSplit<CR>')
--
vim.keymap.set('n','<silent>', 't<C-l> :cd %:p:h<cr>:TestLast<CR>')
vim.keymap.set('n','<silent>', 't<C-g> :cd %:p:h<cr>:TestVisit<CR>')
vim.keymap.set('n','<C-q>', '<Plug>(quickrun)<CR>')
vim.keymap.set('n','<leader>p', ':call print_debug#print_debug()<cr>')
--
vim.keymap.set('v','<Leader>tsl', ':TranslateVisual<CR>')
vim.keymap.set('v','<Leader>tsr', ':TranslateReplace<CR>')
--
vim.keymap.set('c','<C-H>', '<BS>')
vim.keymap.set('c','<C-F>', '<Right>')
vim.keymap.set('c','<C-B>', '<Left>')
--
vim.keymap.set('n','<Leader>cc', '<Plug>(operator-camelize)')
vim.keymap.set('n','<Leader>C', '<Plug>(operator-decamelize)')
vim.keymap.set('n','<silent>', 'w <Plug>CamelCaseMotion_w')
vim.keymap.set('n','<silent>', 'b <Plug>CamelCaseMotion_b')
vim.keymap.set('n','<silent>', 'e <Plug>CamelCaseMotion_e')
vim.keymap.set('n','<silent>', 'ge <Plug>CamelCaseMotion_ge')

vim.keymap.set('n','<leader>zf', ':lua require(\'telekasten\').find_notes()<CR>')
vim.keymap.set('n','<leader>zd', ':lua require(\'telekasten\').find_daily_notes()<CR>')
vim.keymap.set('n','<leader>zg', ':lua require(\'telekasten\').search_notes()<CR>')
vim.keymap.set('n','<leader>zz', ':lua require(\'telekasten\').follow_link()<CR>')
vim.keymap.set('n','<leader>zT', ':lua require(\'telekasten\').goto_today()<CR>')
vim.keymap.set('n','<leader>zW', ':lua require(\'telekasten\').goto_thisweek()<CR>')
vim.keymap.set('n','<leader>zw', ':lua require(\'telekasten\').find_weekly_notes()<CR>')
vim.keymap.set('n','<leader>zn', ':lua require(\'telekasten\').new_note()<CR>')
vim.keymap.set('n','<leader>zN', ':lua require(\'telekasten\').new_templated_note()<CR>')
vim.keymap.set('n','<leader>zy', ':lua require(\'telekasten\').yank_notelink()<CR>')
vim.keymap.set('n','<leader>zc', ':lua require(\'telekasten\').show_calendar()<CR>')
vim.keymap.set('n','<leader>zC', ':CalendarT<CR>')
vim.keymap.set('n','<leader>zi', ':lua require(\'telekasten\').paste_img_and_link()<CR>')
vim.keymap.set('n','<leader>zt', ':lua require(\'telekasten\').toggle_todo()<CR>')
vim.keymap.set('n','<leader>zb', ':lua require(\'telekasten\').show_backlinks()<CR>')
vim.keymap.set('n','<leader>zF', ':lua require(\'telekasten\').find_friends()<CR>')
vim.keymap.set('n','<leader>zI', ':lua require(\'telekasten\').insert_img_link({ i=true })<CR>')
vim.keymap.set('n','<leader>zp', ':lua require(\'telekasten\').preview_img()<CR>')
vim.keymap.set('n','<leader>zm', ':lua require(\'telekasten\').browse_media()<CR>')
vim.keymap.set('n','<leader>za', ':lua require(\'telekasten\').show_tags()<CR>')
vim.keymap.set('n','<leader>#', ':lua require(\'telekasten\').show_tags()<CR>')
vim.keymap.set('n','<leader>zr', ':lua require(\'telekasten\').rename_note()<CR>')
vim.keymap.set('n','<leader>z', ':lua require(\'telekasten\').panel()<CR>')

vim.keymap.set('i','<leader>[', '<cmd>:lua require(\'telekasten\').insert_link({ i=true })<CR>')
vim.keymap.set('i','<leader>zt', '<cmd>:lua require(\'telekasten\').toggle_todo({ i=true })<CR>')
vim.keymap.set('i','<leader>#', '<cmd>lua require(\'telekasten\').show_tags({i = true})<cr>')

vim.keymap.set('v','<silent>', '* :<C-u>call VisualSelection(\'\', \'\')<CR>/<C-R>=@/<CR><CR>')
vim.keymap.set('v','<silent>', '# :<C-u>call VisualSelection(\'\', \'\')<CR>?<C-R>=@/<CR><CR>')
-- " Disable highlight when <leader><cr> is pressed
vim.keymap.set('','<silent>', '<leader><cr> :noh<cr>')
-- " Smart way to move between windows
vim.keymap.set('','<C-j>', '<C-W>j')
vim.keymap.set('','<C-k>', '<C-W>k')
vim.keymap.set('','<C-h>', '<C-W>h')
vim.keymap.set('','<C-l>', '<C-W>l')
vim.keymap.set('','<leader>bd', ':Bclose<cr>:tabclose<cr>gT')
vim.keymap.set('','<leader>ba', ':bufdo bd<cr>')
vim.keymap.set('','<leader>cd', ':cd %:p:h<cr>:pwd<cr>')
vim.keymap.set('','0', '^')
vim.keymap.set('','<leader>ss', ':setlocal spell!<cr>')
vim.keymap.set('','<leader>sa', 'zg')
vim.keymap.set('','<leader>s?', 'z=')
vim.keymap.set('','<Leader>m', 'mmHmt:%s/<C-V><cr>//ge<cr>\'tzt\'m')
