[font]
normal = { family = "Moralerspace Neon HWNF", style = "Regular" }

size = 11.5

[window]
opacity = 0.85

[keyboard]
bindings = [
  { key = "Tab", mods = "Control", action = "SelectNextTab" },
  { key = "Tab", mods = "Control|Shift", action = "SelectPreviousTab" },
  { key = "¥", chars = '\'},
  { key = "¥", mods="Alt", chars = '¥'},
]
